SHELL=/bin/bash
INC=-Iinclude
CC=g++

all: clean prepare build
	@echo "Сборка приложения... завершена"

clean:
	rm -rf bin
	rm -rf obj

prepare:
	mkdir -p bin
	mkdir -p obj

build:
	$(CC) -Wall -g -O0 -c $(INC) -o obj/BankAccount.o src/BankAccount.cpp
	$(CC) -Wall -g -O0 -c $(INC) -o obj/main.o src/main.cpp
	$(CC) -g -O0 -o bin/main obj/BankAccount.o obj/main.o
