SHELL=/bin/bash
INC=-Iinclude
CC=g++

.PHONY: all clean prepare build

all: clean prepare build
	@echo "Building application...done"
	echo $(SHELL)

clean:
	rm -rf bin
	rm -rf obj

prepare:
	mkdir -p bin
	mkdir -p obj

build:
	$(CC) -Wall -g -O0 -c $(INC) -o obj/median.o src/median.cpp
	$(CC) -Wall -g -O0 -c $(INC) -o obj/bubblesort.o src/bubblesort.cpp
	$(CC) -Wall -g -O0 -c $(INC) -o obj/main.o src/main.cpp
	$(CC) -g -O0 -o bin/main.p obj/median.o obj/bubblesort.o obj/main.o

